"""Backward-compatible aggregator for all Pydantic models.

Models live in `models_core.py` (shared/usage/pricing), `models_projects.py`
(Project + Scene), `models_records.py` (feature records), and
`models_infra.py` (uploads, invite codes, AI models). Callers can still do
`from models import X` for any of them.
"""

# noqa: F401 — these are intentional re-exports
from models_core import (
    AIResponseWrapper,
    FeaturePricing,
    PricingEstimateRequest,
    ProjectStatus,
    ServiceLineItem,
    SystemResource,
    SystemResourceInfo,
    SystemResourceType,
    UsageMetrics,
    generate_id,
)
from models_projects import (
    CharacterProfile,
    Continuity,
    GlobalStyle,
    Project,
    Scene,
    SceneMetadata,
)
from models_records import (
    AdaptRecord,
    AdaptVariant,
    FocalPoint,
    KeyMomentModel,
    KeyMomentsRecord,
    PromoRecord,
    PromoSegment,
    ReframeRecord,
    SceneChange,
    SpeakerPosition,
    SpeakerSegment,
    ThumbnailRecord,
    ThumbnailScreenshot,
)
from models_infra import (
    AIModel,
    AVAILABLE_REGIONS,
    CompressedVariant,
    CreateAIModelRequest,
    CreateInviteCodeRequest,
    InviteCode,
    ModelCapability,
    UploadCompleteRequest,
    UploadInitRequest,
    UploadRecord,
    ValidateCodeRequest,
)
from models_avatar import (
    AskAvatarRequest,
    Avatar,
    AvatarStyle,
    AvatarTurn,
    AvatarVersion,
    AvatarVoice,
    CreateAvatarRequest,
)

__all__ = [
    "AIModel",
    "AIResponseWrapper",
    "AVAILABLE_REGIONS",
    "AdaptRecord",
    "AdaptVariant",
    "AskAvatarRequest",
    "Avatar",
    "AvatarStyle",
    "AvatarTurn",
    "AvatarVersion",
    "AvatarVoice",
    "CreateAvatarRequest",
    "CharacterProfile",
    "CompressedVariant",
    "Continuity",
    "CreateAIModelRequest",
    "CreateInviteCodeRequest",
    "FeaturePricing",
    "FocalPoint",
    "GlobalStyle",
    "InviteCode",
    "KeyMomentModel",
    "KeyMomentsRecord",
    "ModelCapability",
    "PricingEstimateRequest",
    "Project",
    "ProjectStatus",
    "PromoRecord",
    "PromoSegment",
    "ReframeRecord",
    "Scene",
    "SceneChange",
    "SceneMetadata",
    "ServiceLineItem",
    "SpeakerPosition",
    "SpeakerSegment",
    "SystemResource",
    "SystemResourceInfo",
    "SystemResourceType",
    "ThumbnailRecord",
    "ThumbnailScreenshot",
    "UploadCompleteRequest",
    "UploadInitRequest",
    "UploadRecord",
    "UsageMetrics",
    "ValidateCodeRequest",
    "generate_id",
]
